// // This file was generated by Prisma, and assumes you have installed the following:
// // npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";
// import dotenv from "dotenv";
// // import ENV from "./src/config/env.config.ts";
// import { databaseUrl } from "./src/config/database.config.ts";

// dotenv.config();



// if (!databaseUrl) {
//   throw new Error("DATABASE_URL environment variable is not set");
// }

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: databaseUrl,
//   },
// });


import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

dotenv.config();

export default defineConfig({

    schema: "prisma/schema.prisma",

    migrations: {
        path: "prisma/migrations"
    },

    datasource: {
        url: process.env.DATABASE_URL ?? ""
    }

});